language: ruby

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql

rvm:
    - 2.5.1

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1

before_script:
  - psql -c 'select version();' # just to check the version, would also allow to check that pg is running
  - psql -c "select * from pg_settings where name = 'port';" # check port settings

script:
    - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
    - bundle exec rspec
    - make dev build push

sudo: required

services:
  - docker

env:
  global:
  - PGPORT=5433
